### ISSUE TITLE
Comments - Matched inside quotes

### ISSUE THREAD

**Issue by MatiasMFM2001** [jo3-l/cc-minifier#1]
I know this is a very edge case, but I was trying the minifier with my `-cc2file` and found the CC "comment" inside `printf`'s format string was deleted. I tested current [comment Regex expression](https://regex101.com/r/936oul/3) and yes, it's being matched. 

Some other Regex I've tried:
- [`[^"\x60]{{(-\s+)?\/\*[\S\s]+?\*\/(\s+-)?}}[^"\x60]`](https://regex101.com/r/lcEOxB/2) works, but matches a whitespace character just before the comment itself
- [`{{(-\s+)?\/\*[^}]+?\*\/(\s+-)?}}`](https://regex101.com/r/yKNXLu/2) works only for my usecase

I've included part of CC's code to have some examples, a bit of everything (edit: I had put *too much code*)

**Comment by jo3-l** [comment]
unfortunately I don't believe this can be fixed completely without using a proper lexer/parser and walking the AST instead of the regex hackery we do currently.
